# Generated by Django 2.2.28 on 2023-01-10 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField()),
                ('created_user', models.UUIDField()),
                ('updated_user', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'difficulty',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField()),
                ('created_user', models.UUIDField()),
                ('updated_user', models.UUIDField()),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'music',
            },
        ),
        migrations.CreateModel(
            name='MusicDifficulty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField()),
                ('created_user', models.UUIDField()),
                ('updated_user', models.UUIDField()),
                ('level', models.IntegerField()),
                ('difficulty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iidx.Difficulty')),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iidx.Music')),
            ],
            options={
                'db_table': 'music_difficulty',
            },
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField()),
                ('created_user', models.UUIDField()),
                ('updated_user', models.UUIDField()),
                ('memo', models.TextField(max_length=1000, null=True)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iidx.Music')),
            ],
            options={
                'db_table': 'memo',
            },
        ),
    ]
