# Generated by Django 2.2.28 on 2023-01-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='difficulty',
            name='created_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='updated_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='created_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='updated_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='created_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='updated_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='musicdifficulty',
            name='created_user',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='musicdifficulty',
            name='updated_user',
            field=models.UUIDField(null=True),
        ),
    ]
