# Generated by Django 4.1.5 on 2023-04-19 03:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iidx', '0002_auto_20230111_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCodeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField()),
                ('created_user', models.UUIDField(null=True)),
                ('updated_user', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'general_code_category',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='GeneralCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.IntegerField()),
                ('created_user', models.UUIDField(null=True)),
                ('updated_user', models.UUIDField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('order', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iidx.generalcodecategory')),
            ],
            options={
                'db_table': 'general_code',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='version',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='iidx.generalcode'),
        ),
        migrations.AlterField(
            model_name='musicdifficulty',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='iidx.generalcode'),
        ),
        migrations.DeleteModel(
            name='Difficulty',
        ),
    ]
